name: upload
on:
    workflow_dispatch:
    schedule:
      - cron: '0 0 1 * *'

jobs:
  issue-ssl-certificate:
    name: Issue SSL certificate
    runs-on: ubuntu-latest

    strategy:
        matrix:
          domain:
              - qncdn.aprdec.top
              - qiniu.aprdec.top

    steps:
      - name: install acme.sh
        shell: bash
        run: curl https://get.acme.sh | sh 
      - name: Extract account files for acme.sh
        shell: bash
        run: |
          echo "$ACME_SH_ACCOUNT_TAR" | base64 -d | tar -C ~/.acme.sh -xz
        env:
          # Base64 编码的 acme.sh 配置信息
          ACME_SH_ACCOUNT_TAR: ${{ secrets.ACME_SH_ACCOUNT_TAR }}
        # 申请证书
      - name: Issue SSL certificates
        shell: bash
        run: |
            ~/.acme.sh/acme.sh --issue --dns dns_tencent -d *.aprdec.top\
            --key-file       /output/key.pem  \
            --fullchain-file /output/cert.pem 

      - name: update qiniu ${{ matrix.domain }}
        uses: foxundermoon/upload-qiniu-cert-action@master
        with:
          ak: ${{ secrets.QINIU_AK }}
          sk: ${{ secrets.QINIU_SK }}
          domain: aprdec.top
          update-domains: |
           .${{ matrix.domain }} | https | http2
           ${{ matrix.domain }} | https | http2
          debug: 'yes'
          cert-path: '/output/cert.pem'
          key-path: '/output/key.pem'
        

